### ISSUE TITLE
Issue with NeMo Model Installation on Python 3.10.12: ImportError from huggingface_hub

### ISSUE THREAD

**Issue by shripadalkar** [AI4Bharat/NeMo#11]
I encountered an issue when trying to install and import the NeMo ASR model on Python 3.10.12. After following the installation steps, I received the following error during the import of the nemo.collections.asr module:
Steps to Reproduce:

steps 1
git clone https://github.com/AI4Bharat/NeMo.git && cd NeMo && git checkout nemo-v2 && bash reinstall.sh
step 2
import nemo.collections.asr as nemo_asr

Error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/collections/asr/losses/__init__.py", line 15, in <module>
    from nemo.collections.asr.losses.angularloss import AngularSoftmaxLoss
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/collections/asr/losses/angularloss.py", line 18, in <module>
    from nemo.core.classes import Loss, Typing, typecheck
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/core/__init__.py", line 16, in <module>
    from nemo.core.classes import *
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/core/classes/__init__.py", line 20, in <module>
    from nemo.core.classes.common import (
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/core/classes/common.py", line 40, in <module>
    from nemo.core.classes.mixins.hf_io_mixin import HuggingFaceFileIO
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/core/classes/mixins/__init__.py", line 28, in <module>
    from nemo.core.classes.mixins.hf_io_mixin import HuggingFaceFileIO
  File "/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/NeMo/nemo/core/classes/mixins/hf_io_mixin.py", line 19, in <module>
    from huggingface_hub import HfApi, ModelCard, ModelCardData, ModelFilter
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' (/home/shrikant/Project/python/ASR/speech_to_text_setup/dec262024/asr/lib/python3.10/site-packages/huggingface_hub/__init__.py)

**Comment by wannasleepforlong** [comment]
Encountered the exact same error. Weirdly enough, it was working earlier in different device

**Comment by AK3847** [comment]
The issue is that the NeMo library has not been maintained for the past 9 months while there have been major changes in the hugginface-hub repo, so you have to downgrade the package version which can lead to version conflict with other packages (transformers, datasets), I tried my best to find set of versions which would work, you can check out here: https://colab.research.google.com/drive/1umnew1cip7XnQkVJ3Edt1QtZB1ZRaaVK?authuser=1#scrollTo=0t9XnTTkjq5l&line=1&uniqifier=1

fix:

```bash
!pip install transformers==4.40.0
!pip install huggingface_hub==0.21.3
!pip install tokenizers>=0.21
!pip install datasets==2.19.0
```

**Comment by shripadalkar** [comment]
@AK3847 Thanks.

**Comment by bhargaviajaypatel** [comment]
> The issue is that the NeMo library has not been maintained for the past 9 months while there have been major changes in the hugginface-hub repo, so you have to downgrade the package version which can lead to version conflict with other packages (transformers, datasets), I tried my best to find set of versions which would work, you can check out here: https://colab.research.google.com/drive/1umnew1cip7XnQkVJ3Edt1QtZB1ZRaaVK?authuser=1#scrollTo=0t9XnTTkjq5l&line=1&uniqifier=1
> 
> fix:
> 
> !pip install transformers==4.40.0
> !pip install huggingface_hub==0.21.3
> !pip install tokenizers>=0.21
> !pip install datasets==2.19.0

it is not working for me... Pls help

**Comment by wannasleepforlong** [comment]
@bhargaviajaypatel Try running this mate 
#!/bin/bash
# python: 3.10.12
python3 -m pip install "pydub"
python3 -m pip install "cython==0.29.37"
python3 -m pip install "pyyaml==6.0.2"
python3 -m pip install "argparse==1.4.0"
python3 -m pip install "onnxruntime==1.19.0"
python3 -m pip install "tqdm==4.66.5"
python3 -m pip install "nemo_toolkit @ git+https://github.com/AI4Bharat/NeMo@nemo-v2"
python3 -m pip install "transformers==4.40.0"
python3 -m pip install "huggingface_hub==0.23"
python3 -m pip install "pytorch-lightning==2.4.0"
python3 -m pip install "hydra-core==1.3.2"
python3 -m pip install "librosa==0.10.2.post1"
python3 -m pip install "sentencepiece==0.2.0"
python3 -m pip install "pandas==2.2.2"
python3 -m pip install "lhotse==1.27.0"
python3 -m pip install "editdistance==0.8.1"
python3 -m pip install "jiwer==3.0.4"
python3 -m pip install "pyannote.audio==3.3.1"
python3 -m pip install "webdataset==0.2.100"
python3 -m pip install "datasets==2.21.0"
python3 -m pip install "IPython==8.27.0"
python3 -m pip install "joblib==1.4.2"
python3 -m pip install "numpy==1.26.4 "
python3 -m pip install "argparse==1.4.0"
python3 -m pip install "moviepy==1.0.3"

**Comment by AK3847** [comment]
@bhargaviajaypatel can you share the versions of installed libraries in your environment? It's most likely a version conflict which can be solved by downgrading python version or some other package.

**Comment by bhargaviajaypatel** [comment]
> [@bhargaviajaypatel](https://github.com/bhargaviajaypatel) can you share the versions of installed libraries in your environment? It's most likely a version conflict which can be solved by downgrading python version or some other package.

I have used the below code... It worked yesterday..but it is not working today...

# Ensure that you delete any previous incomplete installation or corrupted NeMo directory.
!rm -rf NeMo

# Step 1: Clone the NeMo repository
!git clone https://github.com/AI4Bharat/NeMo.git

# Step 2: Change into the NeMo directory
%cd NeMo

# Step 3: Install NeMo, PyTorch Lightning and Hydra-core
!pip install -U pip setuptools
!pip install -e '.[all]'  # install NeMo for editing
!pip install lightning  # Install PyTorch Lightning
!pip install hydra-core # Install Hydra-core

# Step 4: Test the installation
try:
    import nemo
    import nemo.collections.asr as nemo_asr
    print("NeMo successfully installed and imported!")
except ImportError as e:
    print(f"An error occurred: {e}")

**Comment by AK3847** [comment]
> > [@bhargaviajaypatel](https://github.com/bhargaviajaypatel) can you share the versions of installed libraries in your environment? It's most likely a version conflict which can be solved by downgrading python version or some other package.
> 
> I have used the below code... It worked yesterday..but it is not working today...
> 
> # Ensure that you delete any previous incomplete installation or corrupted NeMo directory.
> !rm -rf NeMo
> 
> # Step 1: Clone the NeMo repository
> !git clone https://github.com/AI4Bharat/NeMo.git
> 
> # Step 2: Change into the NeMo directory
> %cd NeMo
> 
> # Step 3: Install NeMo, PyTorch Lightning and Hydra-core
> !pip install -U pip setuptools !pip install -e '.[all]' # install NeMo for editing !pip install lightning # Install PyTorch Lightning !pip install hydra-core # Install Hydra-core
> 
> # Step 4: Test the installation
> try: import nemo import nemo.collections.asr as nemo_asr print("NeMo successfully installed and imported!") except ImportError as e: print(f"An error occurred: {e}")

Can you please provide the error that you are getting?
If it's a package conflict error, check the solution I mentioned in the top of this thread

**Comment by bhargaviajaypatel** [comment]
> > > [@bhargaviajaypatel](https://github.com/bhargaviajaypatel) can you share the versions of installed libraries in your environment? It's most likely a version conflict which can be solved by downgrading python version or some other package.
> > 
> > 
> > I have used the below code... It worked yesterday..but it is not working today...
> > # Ensure that you delete any previous incomplete installation or corrupted NeMo directory.
> > !rm -rf NeMo
> > # Step 1: Clone the NeMo repository
> > !git clone https://github.com/AI4Bharat/NeMo.git
> > # Step 2: Change into the NeMo directory
> > %cd NeMo
> > # Step 3: Install NeMo, PyTorch Lightning and Hydra-core
> > !pip install -U pip setuptools !pip install -e '.[all]' # install NeMo for editing !pip install lightning # Install PyTorch Lightning !pip install hydra-core # Install Hydra-core
> > # Step 4: Test the installation
> > try: import nemo import nemo.collections.asr as nemo_asr print("NeMo successfully installed and imported!") except ImportError as e: print(f"An error occurred: {e}")
> 
> Can you please provide the error that you are getting? If it's a package conflict error, check the solution I mentioned in the top of this thread

Thank you for the effort... The problem is now resolved... Now I am trying to bring the code on the local machine...
